export const POST_PROVIDER_LOGIN = "POST_PROVIDER_LOGIN";
export const POST_PROVIDER_LOGIN_SUCCEED = "POST_PROVIDER_LOGIN_SUCCEED";
export const POST_PROVIDER_LOGIN_FAIL = "POST_PROVIDER_LOGIN_FAIL";

export const OPEN_MESSAGE = "OPEN_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";

export const POST_INITIALIZE_ENCOUNTER = "POST_INITIALIZE_ENCOUNTER";
export const POST_INITIALIZE_ENCOUNTER_SUCCEED = "POST_INITIALIZE_ENCOUNTER_SUCCEED";
export const POST_INITIALIZE_ENCOUNTER_FAIL = "POST_INITIALIZE_ENCOUNTER_FAIL";

export const POST_PREPARE_ENCOUNTER = "POST_PREPARE_ENCOUNTER";
export const POST_PREPARE_ENCOUNTER_SUCCEED = "POST_PREPARE_ENCOUNTER_SUCCEED";
export const POST_PREPARE_ENCOUNTER_FAIL = "POST_PREPARE_ENCOUNTER_FAIL";

export const POST_READY_ENCOUNTER = "POST_READY_ENCOUNTER";
export const POST_READY_ENCOUNTER_SUCCEED = "POST_READY_ENCOUNTER_SUCCEED";
export const POST_READY_ENCOUNTER_FAIL = "POST_READY_ENCOUNTER_FAIL";

export const POST_POSTPONE_ENCOUNTER = "POST_POSTPONE_ENCOUNTER";
export const POST_POSTPONE_ENCOUNTER_SUCCEED = "POST_POSTPONE_ENCOUNTER_SUCCEED";
export const POST_POSTPONE_ENCOUNTER_FAIL = "POST_POSTPONE_ENCOUNTER_FAIL";

export const BATCH_ENCOUNTER = "BATCH_ENCOUNTER";
export const BATCH_ENCOUNTER_SUCCEED = "BATCH_ENCOUNTER_SUCCEED";
export const BATCH_ENCOUNTER_FAIL = "BATCH_ENCOUNTER_FAIL";

export const POST_INTAKE = "POST_INTAKE";
export const POST_INTAKE_SUCCEED = "POST_INTAKE_SUCCEED";
export const POST_INTAKE_FAIL = "POST_INTAKE_FAIL";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCEED = "SEND_MESSAGE_SUCCEED";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const GET_MESSAGE = "GET_MESSAGE";
export const GET_MESSAGE_SUCCEED = "GET_MESSAGE_SUCCEED";
export const GET_MESSAGE_FAIL = "GET_MESSAGE_FAIL";

export const GET_NOTES = "GET_NOTES";
export const GET_NOTES_SUCCEED = "GET_NOTES_SUCCEED";
export const GET_NOTES_FAIL = "GET_NOTES_FAIL";